name: Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: List repo tree (src, data, includes)
        run: |
          echo "== src ==" && ls -la src || true
          echo "== src/_includes ==" && ls -la src/_includes || true
          echo "== src/_includes/layouts ==" && ls -la src/_includes/layouts || true
          echo "== src/_data ==" && ls -la src/_data || true
          echo "== show index.njk head ==" && head -n 30 src/index.njk || true

      - name: Fetch deals (non-blocking)
        run: node scripts/fetch_deals.js || true

      - name: Build Eleventy (record exit code)
        run: |
          set +e
          npx @11ty/eleventy
          CODE=$?
          echo "ELEVENTY_EXIT=$CODE" >> $GITHUB_ENV
          set -e

      - name: Ensure _site and fallbacks
        run: |
          mkdir -p _site
          if [ ! -f "_site/index.html" ] && [ -f "index.html" ]; then cp index.html _site/index.html; fi
          if [ ! -f "_site/feed.xml" ]; then echo '<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>CuponBarta — Fallback Feed</title><link>https://cuponbarta.github.io/CuponBarta/</link><description>Fallback</description><language>bn-BD</language></channel></rss>' > _site/feed.xml; fi
          if [ ! -f "_site/sitemap.xml" ]; then echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://cuponbarta.github.io/CuponBarta/</loc><changefreq>hourly</changefreq></url></urlset>' > _site/sitemap.xml; fi
          touch _site/.nojekyll
          echo "== _site listing ==" && ls -la _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
