name: Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '5 21 * * *' # Daily 03:05 BD time (21:05 UTC)

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fetch deals from Google Sheets (non-blocking)
        run: node scripts/fetch_deals.js
        continue-on-error: true

      - name: Build Eleventy (non-blocking)
        run: npx @11ty/eleventy
        continue-on-error: true

      - name: Ensure _site exists and fallback homepage
        run: |
          mkdir -p _site
          if [ ! -f "_site/index.html" ] && [ -f "index.html" ]; then
            cp index.html _site/index.html || true
          fi

      - name: Ensure fallback feed.xml and sitemap.xml
        run: |
          mkdir -p _site
          if [ ! -f "_site/feed.xml" ]; then
            cat > _site/feed.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
  <title>CuponBarta — Deals</title>
  <link>https://cuponbarta.github.io/CuponBarta/</link>
  <description>Latest verified deals and coupons for Bangladesh (fallback feed).</description>
  <language>bn-BD</language>
</channel>
</rss>
EOF
          fi
          if [ ! -f "_site/sitemap.xml" ]; then
            cat > _site/sitemap.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://cuponbarta.github.io/CuponBarta/</loc>
    <changefreq>hourly</changefreq>
  </url>
</urlset>
EOF
          fi
          echo "Built files in _site:"
          ls -la _site || true

      - name: Disable Jekyll
        run: touch _site/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

