nname: Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fetch deals (non-blocking)
        run: node scripts/fetch_deals.js || true

      - name: Build Eleventy (non-blocking)
        run: npx @11ty/eleventy || true

      - name: Ensure _site and fallback files
        run: |
          mkdir -p _site
          # If Eleventy didn't produce index.html, copy root fallback
          if [ ! -f "_site/index.html" ] && [ -f "index.html" ]; then
            cp index.html _site/index.html
          fi
          # Always ensure feed.xml and sitemap.xml exist (simple fallbacks)
          if [ ! -f "_site/feed.xml" ]; then
            cat > _site/feed.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
  <title>CuponBarta — Deals (Fallback)</title>
  <link>https://cuponbarta.github.io/CuponBarta/</link>
  <description>Fallback RSS feed. Replaced when Eleventy build succeeds.</description>
  <language>bn-BD</language>
</channel>
</rss>
EOF
          fi
          if [ ! -f "_site/sitemap.xml" ]; then
            cat > _site/sitemap.xml << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://cuponbarta.github.io/CuponBarta/</loc>
    <changefreq>hourly</changefreq>
  </url>
</urlset>
EOF
          fi
          # Jekyll off
          touch _site/.nojekyll
          echo "Built files in _site:" && ls -la _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
